# Generated by Django 2.1.4 on 2018-12-17 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='uuid',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
