# Generated by Django 2.1.4 on 2019-04-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190129_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='last_logged_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_logged_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_received_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='last_received_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='log_interval',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='sensor',
            name='logging',
            field=models.BooleanField(default=False),
        ),
    ]
