# Generated by Django 2.1.4 on 2019-12-29 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190411_0400'),
    ]

    operations = [
        migrations.CreateModel(
            name='MayorOIgualRegla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRange', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('umbral', models.FloatField(default=0.0)),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas', to='api.Sensor')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
