# Generated by Django 2.1.4 on 2019-12-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0006_mayoroigualregla'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripion', models.TextField()),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Regla',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataRange', models.IntegerField(default=0)),
                ('descripcion', models.TextField()),
                ('umbral', models.FloatField(default=0.0)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.regla_set+', to='contenttypes.ContentType')),
                ('sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas', to='api.Sensor')),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mayoroigualregla',
            options={'base_manager_name': 'objects'},
        ),
        migrations.RemoveField(
            model_name='mayoroigualregla',
            name='dataRange',
        ),
        migrations.RemoveField(
            model_name='mayoroigualregla',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='mayoroigualregla',
            name='id',
        ),
        migrations.RemoveField(
            model_name='mayoroigualregla',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='mayoroigualregla',
            name='umbral',
        ),
        migrations.CreateModel(
            name='ConsolaMensajero',
            fields=[
                ('mensajero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Mensajero')),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('api.mensajero',),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_api.mensajero_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='regla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajeros', to='api.Regla'),
        ),
        migrations.AddField(
            model_name='mayoroigualregla',
            name='regla_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Regla'),
            preserve_default=False,
        ),
    ]
