# Generated by Django 2.1.4 on 2020-01-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191229_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMensajero',
            fields=[
                ('mensajero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Mensajero')),
                ('destinatario', models.TextField()),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('api.mensajero',),
        ),
        migrations.CreateModel(
            name='MenorOIgualRegla',
            fields=[
                ('regla_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Regla')),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('api.regla',),
        ),
        migrations.CreateModel(
            name='SmsMensajero',
            fields=[
                ('mensajero_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.Mensajero')),
                ('destinatario', models.TextField()),
            ],
            options={
                'base_manager_name': 'objects',
                'abstract': False,
            },
            bases=('api.mensajero',),
        ),
        migrations.AddField(
            model_name='mensajero',
            name='premensaje',
            field=models.TextField(default='mensaje'),
            preserve_default=False,
        ),
    ]
