# Generated by Django 2.1.4 on 2020-01-09 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200108_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mensajero',
            old_name='descripion',
            new_name='descripcion',
        ),
    ]
