# Generated by Django 2.1.4 on 2020-01-09 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200109_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verificando', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lectura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturas', to='api.Lectura')),
            ],
        ),
        migrations.AlterField(
            model_name='regla',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='api.Sensor'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='logging',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='regla',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.Regla'),
        ),
    ]
