# Generated by Django 2.1.4 on 2020-01-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200109_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='regla',
        ),
        migrations.AddField(
            model_name='alerta',
            name='descripcion',
            field=models.TextField(default='alerta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alerta',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='api.Sensor'),
        ),
    ]
