# Generated by Django 2.1.4 on 2020-01-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200109_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='umbral',
            field=models.FloatField(default=0.0),
        ),
    ]
